### ISSUE TITLE
HSDA 2.0 notes

### ISSUE THREAD

**Issue by soundpress** [openreferral/api-specification#111]
Hi,

I was asked to leave my comments as I created several applications based on HSDA 1.1.1 about a year ago.
At first let me thank you for clear documentation - it is really easy to work with it.

As for new version - here are my thoughts:

## openapi-hsda.yaml

It seems you removed all /complete paths but they are very useful. While building services directory API was mostly requested via these paths which significantly optimized performance. Moreover for keeping performance high I had to expand schema for /services/complete/{id} responce and include also related /organization, /location and /taxonomy (!) objects

## openapi-hsda-taxonomy.yaml

Paths
- /{taxonomy_name}/services/
- /{taxonomy_name}/organizations/
- /{taxonomy_name}/locations/
	
.. may be broken if {taxonomy_name} is meta, search, organizations etc. stored in taxonomy data or came from user input. So developer will have to implement sophisticated matching/protection for API requests and taxonomy data. 

Switching paths to /taxonomies/{taxonomy_name}/services/ or so will help to bypass that

Regards,
Maxim Pokrovsky

**Comment by mrshll1001** [comment]
We will be arching this repository soon. We're closing this issue because we believe it has been conclusively addressed as part of work on the main HSDS standard.

In this case, the HSDS 3.0 API specification contains endpoints for retrieving these objects, as well as allowing querying on other endpoints by taxonomy ids and taxonomy_term ids.
