### ISSUE TITLE
hsda taxonomy sub-elements

### ISSUE THREAD

**Issue by kinlane** [openreferral/api-specification#73]
now that we have a taxonomy system for adding, editing, and managing taxonomy. We can add back sub-elements of taxonomy to the full results, and add endpoints for /services/taxonomy.  These are optional aspects of the core spec that will only be available when the HSDA taxonomy is present.

**Comment by kinlane** [comment]
I added taxonomies to HSDA, adding the following paths:

/services/{service_id}/taxonomies/
/services/{service_id}/taxonomies/{taxonomy_id}/
/services/complete/{service_id}/taxonomies/
/services/complete/{service_id}/taxonomies/{taxonomy_id}/

As well as the definition for taxonomy, which has been in HSDS, but never introduced to HSDA.

Now that we have this in here you can add, remove taxonomies from services, which will then allow it to be searched.

You can find the OpenAPI for this here: https://gist.github.com/kinlane/dcac462b4c6b7c058b23d381cf3e6f23

**Comment by greggish** [comment]
@kinlane I jotted this note in response to [your post](https://github.com/openreferral/api-specification/issues/46#issuecomment-427605250) in #46, but on second thought, adding here:

A taxonomy is comprised of categories. (Or types. Or values. Or codes. Etc.) I don't think we should use 'taxonomies' to refer to 'categories,' if that's what's happening here. 'Taxonomy codes' maybe, although 'type' or 'category' might be more universal across taxonomies. 

'Taxonomies' presumably would refer to multiple distinct taxonomies each with their own codelists, rather than a set of codes within a given taxonomy.

**Comment by kinlane** [comment]
Published the new taxonomy schema - https://www.postman.com/api-evangelist/workspace/open-referral-human-services-data-api-hsda/collection/35240-fe401428-96ce-43c8-99a2-ca13929e71a5?ctx=documentation -- rendering some of this obsolete. Will rely on new issues.
