### ISSUE TITLE
On docs.openreferral.org, OpenAPI Viewer "Try it Out" feature doesn't return data

### ISSUE THREAD

**Issue by greggish** [openreferral/api-specification#79]
So [we have a reference implementation here](http://developer.open.referral.adopta.agency/), and the [HSDA documentation site points users to it](http://docs.openreferral.org/en/latest/hsda/#reference-implementation).

However, in [the documentation sections for each component](http://docs.openreferral.org/en/latest/hsda/#components), there is also a link to "explore this using our OpenAPI viewer" which leads to [a handy Swagger skin](http://docs.openreferral.org/en/latest/_static/swagger/?url=../openapi-hsda.yaml) that is just like the reference implementation, but does not return live data.

We could either figure out how to implement a proper demo environment there, or we could change each of those "explore this" links to point to the respective part of the reference implementation (linked above). 

Suggestions, @timgdavies @Bjwebb @kinlane ?

**Comment by kinlane** [comment]
I submitted a pull request and removed reference implementation section -- until we have a strong one we shouldn't have it. I am working to add a v2.0 reference implementation as soon as possible, and then we can add back in.

**Comment by mrshll1001** [comment]
We will be archiving this repository soon. We're closing this issue because we believe it has been conclusively addressed as part of work on the main HSDS standard.

In this case there is a swagger ui for the new API spec functioning [here](http://docs.openreferral.org/en/latest/openapi.html) as well as a dedicated api reference view in the docs
