### ISSUE TITLE
HSDA Search Taxonomies

### ISSUE THREAD

**Issue by kinlane** [openreferral/api-specification#95]
Adding the ability to search for taxonomies across core resources (organization, locations, and services) in HSDA Search.

  - Issue: https://github.com/openreferral/api-specification/issues/46#issuecomment-427622362 
  - OpenAPI: https://gist.github.com/kinlane/2042c0b2e6a50cddf0039d4bb144cb50

**Comment by NeilMcKechnie** [comment]
This looks like a duplicate to issue #94 https://github.com/openreferral/api-specification/issues/94 .

**Comment by kinlane** [comment]
Not a duplicate. HSDA Taxonomies has its own basic search, as well as augmenting the HSDA Search (advanced) with taxonomy search as well.

**Comment by mrshll1001** [comment]
We will be archiving this repository soon. We're closing this issue because we believe it has been conclusively addressed as part of work on the main HSDS standard.

In this case, we have mopved away from /search endpoints in the HSDS 3.0 specification.

Each other endpoint e.g. `/services` may be queried using `taxonomy_id`, `taxonomy_term_id`, and `search` parameters.

If there is further discussion or clarification about how the search should be augmented, please raise an issue on the [OR specification issue tracker]( https://github.com/openreferral/specification/issues)
